// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/autom8ter/grpcx/providers (interfaces: ContextTagger)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	providers "github.com/autom8ter/grpcx/providers"
	gomock "github.com/golang/mock/gomock"
)

// MockContextTagger is a mock of ContextTagger interface.
type MockContextTagger struct {
	ctrl     *gomock.Controller
	recorder *MockContextTaggerMockRecorder
}

// MockContextTaggerMockRecorder is the mock recorder for MockContextTagger.
type MockContextTaggerMockRecorder struct {
	mock *MockContextTagger
}

// NewMockContextTagger creates a new mock instance.
func NewMockContextTagger(ctrl *gomock.Controller) *MockContextTagger {
	mock := &MockContextTagger{ctrl: ctrl}
	mock.recorder = &MockContextTaggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextTagger) EXPECT() *MockContextTaggerMockRecorder {
	return m.recorder
}

// TagContext mocks base method.
func (m *MockContextTagger) NewTags(arg0 context.Context) providers.Tags {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTags", arg0)
	ret0, _ := ret[0].(providers.Tags)
	return ret0
}

// TagContext indicates an expected call of TagContext.
func (mr *MockContextTaggerMockRecorder) TagContext(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTags", reflect.TypeOf((*MockContextTagger)(nil).NewTags), arg0)
}
